### ISSUE TITLE
Starting an application through SwiftPM does not show terminal colours

### ISSUE THREAD

**Issue by Joannis** [apple/swift-package-manager#6813] opened 2023-08-15 10:45 UTC
### Description

If you start an application through `swift run` or `swift test`, any terminal colours emitted by your application are not shown in the terminal.

### Expected behavior

Terminal colours emitted by my library or executable are correctly emitted into the Terminal when running through SwiftPM.

### Actual behavior

All output is stripped of colours.

### Steps to reproduce

1. Create an application using Vapor's [ConsoleKit](https://github.com/vapor/console-kit)
2. Bootstrap`ConsoleLogger` to the `LoggingSystem` (swift-log)
3. Emit a log line, for example an error.

The line's log level should be coloured, but is not.

### Swift Package Manager version/commit hash

Swift Package Manager - Swift 5.9.0

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.87 Apple Swift version 5.9 (swiftlang-5.9.0.124.4 clang-1500.0.38.1)
Target: arm64-apple-macosx14.0

**Comment by neonichu** [comment] 2023-08-15 16:02
duplicate of https://github.com/apple/swift-package-manager/issues/6081

**Closed by neonichu** 2023-08-15 16:02 UTC
Labels: bug
