### ISSUE TITLE
[SR-15876] Unhelpful error: Could not build Objective-C module ‘ModuleName’

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-package-manager#5925] opened 2022-02-17 14:10 UTC
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15876      |
   |Radar             | rdar://89082987         |
   |Original Reporter | @ahoppen      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 2         |
   |Component/s       | SourceKit-LSP    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 9ddcee184f7c88e97c4a2a1e791ed8aa

  </details>

**Issue Description:**

From <https://forums.swift.org/t/unhelpful-error-could-not-build-objective-c-module-modulename/55381>

Sometimes when loading a package into the VSCode extension the SourceKit-LSP server will return the error

``` java
Could not build Objective-C module 'ModuleName'
```

where ModuleName is the name of some module being imported. This error appears on modules regardless of whether they include any Objective-C or not. Unfortunately I haven't found a consistent way to replicate this error. It appears to disappear if you build the project and restart VSCode. If it is related to the relevant module not being built it is not a very helpful message.

In what situations is this error message meant to appear.

**Comment by hassila** [comment] 2022-11-24 09:01
Running `swift test` a second time give the also unhelpful error:
```
hassila@ice ~/G/package-benchmark ((0.3.2)) [1]> swift test
Compiling plugin Benchmark-Plugin...
Compiling plugin GenerateManualPlugin...
Building for debugging...
<unknown>:0: error: missing required module '_NumericsShims'
<unknown>:0: error: missing required module '_NumericsShims'
```

In this case the error is a missing dependency - we've found out that missing dependencies often gives these errors of 'missing required module xxx' which perhaps could be improved (the error isn't really "could not build Objective-C module", but should be something like "Can't import a module we have no dependency for" or something).

Adding the dependency fixes the error:
```
        .testTarget(
            name: "BenchmarkTests",
            dependencies: ["BenchmarkSupport"]
        ),
```

@ahoppen - maybe my reproducer was not valid for the original issue with sourcekit-lsp and a bit of a red herring for the original issue - even if it would be nice with a better diagnostic for my case too.

**Comment by chienpm304** [comment] 2023-02-26 07:17
If you are using M1, it seems like the launch task is not correct, so the module is build wrongly. Can check the folder `.build/arm64-apple-macosx`

**Comment by MikePendo** [comment] 2023-03-10 15:49
I have a similar error 
```
could not build Objective-C module 'Module'
umbrella header 'Module.h' not found
```
Which caused by adding swift file to objc Framework 
Its a different case than the one in the ticket **BUT** why the error is so ambiguous why the error doesnt includes a proper description of why it happens so we could understand the problem and fix _maybe fix it_

**Comment by code-per-day** [comment] 2023-10-16 21:51
Any guidance on finding out what issue could be causing this error message?

**Comment by neonichu** [comment] 2023-10-16 22:27
The issue will almost always be an unexpressed dependency, potentially using `swift build --explicit-target-dependency-import-check warn` can help with finding it.

**Comment by dabrahams** [comment] 2023-11-07 16:25
How is that warning (at **least** a warning, please!) not on by default??

**Comment by tomerd** [comment] 2023-11-08 18:15
cc @artemcm

**Comment by neonichu** [comment] 2024-01-12 19:01
Should be fixed by https://github.com/apple/swift-package-manager/pull/7103 because the compiler should not be picking up random modules anymore.

**Closed by neonichu** 2024-01-12 19:01 UTC
